var datiVersion = "0.53";
// Colori delle due razze. ⚠️ Valori PROVVISORI: chiari e desaturati per scelta
// dell'utente, ma da misurare sul gate di contrasto AA nei due temi.
// ⚠️ Questa riga VINCE sul fallback dentro index.html: e' la configurazione salvata,
// e al cambio di tavolozza (2026-08-21) i valori vecchi restavano attivi mentre il
// fallback diceva un'altra cosa. Chi cambia una tinta la cambia QUI.
// Quattro famiglie e tre categorie: la tinta degli umani segue il genere (vedi
// `familyOf`), quella degli animali no, perché fra loro il genere manca spesso.
var cardColors = {"fam":{"man":{"dark":"#9cb2f0","light":"#22449c"},"woman":{"dark":"#6fd0d6","light":"#0c757e"},"dragon":{"dark":"#e0a090","light":"#a8462f"},"animale":{"dark":"#e6c445","light":"#856508"}},"map":{"type-man":"man","type-dragon":"dragon","type-animale":"animale"}};
var siteFlags = {"zoomBig":false,"glow":{"on":true,"all":true,"pl":true,"pr":false,"ps":false,"pa":false,"amp_d":60,"amp_l":60,"int_d":0.18,"int_l":0.18,"oamp_d":11,"oamp_l":40,"oint_d":0.9,"oint_l":0.22,"aamp_d":20,"aamp_l":20,"aint_d":0.3,"aint_l":0.11},"glow_m":{"on":true,"all":false,"pl":true,"pr":false,"ps":false,"pa":false,"amp_d":34,"amp_l":34,"int_d":0.62,"int_l":0.5,"oamp_d":11,"oamp_l":11,"oint_d":0.9,"oint_l":0.69,"aamp_d":20,"aamp_l":20,"aint_d":0.3,"aint_l":0.22},"spot":{"on":false,"r":170,"int":0.09},"spot_m":{"on":true,"r":170,"int":0.09},"press":{"on":true,"name":true,"lab":true,"num":true},"press_m":{"on":true,"name":true,"lab":true,"num":false},"vig":{"on":true,"int":0.25,"start":38},"vig_m":{"on":true,"int":0.34,"start":38},"podium":{"on":false,"int_d":1,"int_l":1,"lum_d":1,"lum_l":1,"sat_d":1,"sat_l":1,"top_d":0.7,"top_l":0.7,"rifl_d":0.8,"rifl_l":0.8,"crisp_d":0,"crisp_l":0,"tamp_d":18,"tamp_l":18},"podium_m":{"on":true,"int_d":1,"int_l":1,"lum_d":1,"lum_l":1,"sat_d":1,"sat_l":1,"top_d":0.7,"top_l":0.7,"rifl_d":0.8,"rifl_l":0.8,"crisp_d":0,"crisp_l":0,"tamp_d":18,"tamp_l":18},"nums":{"on":true,"uni":false,"dsat":0.55,"dlum":0.78,"lsat":0.5,"llum":0.52},"nums_m":{"on":true,"uni":true,"dsat":0.15,"dlum":0.66,"lsat":0.15,"llum":0.6},"hov":{"on":true,"bd":true,"op_d":0.09,"op_l":0.08,"sat_d":0.55,"sat_l":0.5,"lum_d":1,"lum_l":1.12},"hov_m":{"on":true,"bd":true,"op_d":0.18,"op_l":0.11,"sat_d":1,"sat_l":1,"lum_d":1,"lum_l":1},"pat":{"on":true,"mot":"banner","c_d":"#ffffff","op_d":0.08,"c_l":"#000000","op_l":0.1,"sc":1,"fade":130},"pat_m":{"on":false,"mot":"stars","c_d":"#ffffff","op_d":0.055,"c_l":"#000000","op_l":0.05,"sc":1,"fade":120}};
// ⚠️⚠️ LO SCHEDARIO È IMPORTATO (0.52, 2026-08-23): le 100 schede compilate dall'utente
// sono entrate (80 voci nuove, 20 aggiornate), sopra le 40 della 0.51. La colonna italiana
// è dello Schedario, cioè dell'utente, coi nomi Nord dove divergono da Mondadori; la metà
// inglese (nome_en, nomi_alternativi_en, appellativi_en) è ATTESTATA sulle fonti col grep,
// non tradotta. Ogni scheda è passata da una verifica sugli epub; le divergenze trovate
// NON sono state corrette d'ufficio: stanno nel brief e decide l'utente.
// ⚠️ Il badge `nomeged` ('Custode del vero nome di Ged') è acceso sulle DIECI voci che il
// canone elenca (`rules/Earthsea.md`, § 'Chi conobbe il vero nome di Sparviero'): Ogion,
// Kurremkarmerruk, Veccia, Millefoglie, Goha, Arren, Therru, Dote, Orm Embar, Kalessin.
// Quel file è la sua UNICA fonte: non si deduce dalle schede. Sparviero NON lo porta:
// il badge marca chi ricevette in custodia il suo nome, non chi lo porta.
// ⚠️ `arcimago` è acceso su Sparviero, Nemmerle e Gensher, i tre che le fonti nominano
// (`rules/Earthsea.md`, § 'Gli Arcimaghi che le fonti nominano'). Thorion NON lo porta:
// fu Maestro delle Evocazioni e governò la scuola, ma non fu mai scelto Arcimago.
// ⚠️ `signoredraghi` è acceso su Sparviero, Erreth-Akbe, Morred e Pannocchia (elenco
// dell'utente; attestazioni e gradi di prova in `rules/Earthsea.md`, § 'Signore dei
// Draghi'). Chi è drago NON lo porta: Tehanu, Orm Irian, Kalessin e Orm Embar restano
// fuori per criterio, non per dimenticanza.
// ⚠️ `maestro` è acceso sui Maestri di Roke che le fonti attestano col titolo accanto al
// nome: Azver, Azzardo, Brand, Deyala, Kurremkarmerruk, Lontra, Nemmerle, Thorion. Il titolo sta anche in `appellativi`; gli appellativi dei nove
// Maestri stanno in `rules/Earthsea.md`, § 'I nove Maestri di Roke'.
// ⚠️⚠️ I DRAGHI PURI hanno SOLO il vero nome: `vero_nome` pieno, `nome` e `nome_en` VUOTI
// (raddrizzato nella 0.52: il vuoto non è una lacuna, è l'informazione che un drago non
// ha nome d'uso). Le due IBRIDE (Therru/Tehanu, Libellula/Orm Irian) seguono la regola
// umana nella RESA (nome d'uso davanti, vero nome sotto) e appartengono a ENTRAMBE le
// categorie (`Donna | Drago`): due livelli indipendenti, ed è una scelta dell'utente.
// ⚠️ IL GENERE DEI DRAGHI È PIENO SU TRE VOCI SOLE (Tehanu e Orm Irian femmine perché
// sono donne oltre che draghi, Ammaud maschio perché è Orm Irian a chiamarlo fratello) e
// le altre restano vuote di proposito: criterio e frase del canone in `rules/Earthsea.md`,
// § 'Il genere dei draghi: congettura, non dato'.
// ⚠️ Su SETTE voci che lo Schedario lasciava col punto di domanda il genere è ora MASCHIO:
// Ath, Faggio, Barbanera, Brand, Azzardo e Hara per la convenzione del canone (chi è detto
// mago o stregone è uomo, `rules/Earthsea.md`, § 'Il vocabolario del potere ha un GENERE:
// mago e stregone sono uomini'), Corvo per i pronomi del testo (Il Trovatore).
// ⚠️ `origine` è la NASCITA quando è attestata e la residenza come ripiego (criterio in
// `CLAUDE.md`, § 'Origine: significa NASCITA, e la residenza è solo un ripiego'); il punto
// di domanda dello Schedario diventa campo VUOTO, che è un dato e non una lacuna da
// riempire. Per gli animali vale la residenza (`Gont`), come per Sula (`Taon`).
// ⚠️ `fonte`/`fonte_en` è l'opera di PRIMA APPARIZIONE nel formato `Titolo (anno)`, coi
// titoli italiani Mondadori del canone; per i racconti vale l'anno del racconto, non
// della raccolta (`La legge dei nomi (1964)`, `Libellula (1997)`, `Rosascura e
// Diamante (1999)`).
// ⚠️ `tipo` di un animale è l'ANIMALE VERO (`Gatta`, `Gallo`), non la categoria: la
// categoria unica 'Animali' la ricava il motore dall'elenco `TIPI_ANIMALE` in
// `index.html`, ed è là che va aggiunto un animale nuovo, o la sua card finisce fra gli
// uomini senza dare alcun errore.
var dati = [
{"nome":"Sparviero","nome_en":"Sparrowhawk","vero_nome":"Ged","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Falco, Duny, Sparviere","nomi_alternativi_en":"Hawk, Duny","appellativi":"Arcimago di Roke, Signore dei Draghi","appellativi_en":"Archmage of Roke, dragonlord","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"signoredraghi":true,"arcimago":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ogion","nome_en":"Ogion","vero_nome":"Aihal","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Il Taciturno","nomi_alternativi_en":"the Silent","appellativi":"Maestro di Ged","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Veccia","nome_en":"Vetch","vero_nome":"Estarriol","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Iffish","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Millefoglie","nome_en":"Yarrow","vero_nome":"Kest","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Iffish","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Yarrow","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Goha","nome_en":"Goha","vero_nome":"Tenar","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Terre di Kargad","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Arha, Signora Bianca, Tenar dell'Anello","nomi_alternativi_en":"Arha, the White Lady, Tenar of the Ring","appellativi":"Alta Sacerdotessa delle Tombe di Atuan, La Divorata","appellativi_en":"high priestess of the Tombs of Atuan, the Eaten One","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Arren","nome_en":"Arren","vero_nome":"Lebannen","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Enlad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Re Promesso, Portatore della Spada di Serriadh","nomi_alternativi_en":"wielder of the Sword of Serriadh","appellativi":"Re di Terramare, Re di Havnor, Principe di Enlad, Erede di Morred","appellativi_en":"King of Earthsea, Prince of Enlad, heir of Morred","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Therru","nome_en":"Therru","vero_nome":"Tehanu","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna | Drago","tipo_en":"Woman | Dragon","tipo_color":"type-donnadrago|","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Dote","nome_en":"Gift","vero_nome":"Emer","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"Semel","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Dono","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Orm Embar","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Selidor","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"","nome_en":"","vero_nome":"Kalessin","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Selidor","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"Segoy, Il più Antico","nomi_alternativi_en":"Segoy, the Eldest","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"","nome_en":"","vero_nome":"Yevaud","fonte":"La legge dei nomi (1964)","fonte_en":"The Rule of Names (1964)","origine":"Pendor","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"Minaccia dell'Ovest, Drago di Pendor","nomi_alternativi_en":"the Dragon of Pendor","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Lontra","nome_en":"Otter","vero_nome":"Medra","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Sterna, Trovatore","nomi_alternativi_en":"Tern, the Finder","appellativi":"Fondatore della Scuola di Roke, Primo Maestro Guardiano","appellativi_en":"Doorkeeper","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Giaggiolo","nome_en":"Flag","vero_nome":"Anieb","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Gelluk","nome_en":"Gelluk","vero_nome":"Tinaral","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Brace","nome_en":"Ember","vero_nome":"Elehal","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Roke","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Early","nome_en":"Early","vero_nome":"Teriel","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Diamante","nome_en":"Diamond","vero_nome":"Essiri","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Burrone","nome_en":"Otak","vero_nome":"Irioth","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Otak","nomi_alternativi_en":"Gully","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Solevivo","nome_en":"Sunbright","vero_nome":"Ayeth","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"Semel","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sege","nome_en":"Sege","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Principe della Casa di Havnor","appellativi_en":"Prince of the House of Havnor","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Tosla","nome_en":"Tosla","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Grigina","nome_en":"Little Grey","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gatta","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gatta di zia Muschio","info_en":"Aunty Moss's cat","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Nerone","nome_en":"Old Black","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Gatto","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gatto di zia Muschio","info_en":"Aunty Moss's cat","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Biddy","nome_en":"Biddy","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di zia Muschio","info_en":"Aunty Moss's hen","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Fioccodineve","nome_en":"Snowflakes","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di zia Muschio","info_en":"Aunty Moss's hen","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Vaiavanti","nome_en":"Gobefore","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Cane","tipo_en":"Dog","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Cane della zia di Sparviero, a Dieci Ontani","info_en":"Sparrowhawk's aunt's dog, at Ten Alders","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Tiro","nome_en":"Tug","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"","padre":"","madre":"Grigina","madre_en":"Little Grey","tipo":"Gatto","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Bucca Rossa","nome_en":"Red Bucca","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Bucca Bruna","nome_en":"Brown Bucca","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Grigia","nome_en":"Grey","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Candore","nome_en":"Candor","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Ghette","nome_en":"Leggings","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Il Re","nome_en":"The King","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Gallo","tipo_en":"Rooster","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallo di Heleth, a Re Albi","info_en":"Heleth's rooster, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Keor","nome_en":"Keor","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Enlad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Principe di Enlad","appellativi_en":"Prince of Enlad","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sula","nome_en":"Gannet","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Taon","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Bar Oth","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"","nome_en":"","vero_nome":"Ammaud","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"","nome_en":"","vero_nome":"Orm","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Selidor","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"L'Antico","nomi_alternativi_en":"","appellativi":"Uccisore di Erreth-Akbe","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"","nome_en":"","vero_nome":"Akambar","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Way","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Re di Terramare, Re di Tutte le Isole","appellativi_en":"King of Earthsea, King of All the Isles","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Mago Nero","nome_en":"Black Mage","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Akaren","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Lorbanery","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Ard","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Perregal","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestra di Heleth","appellativi_en":"Mage of Perregal","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Ath","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ayo","nome_en":"Ayo","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Azver","nome_en":"Azver","vero_nome":"","fonte":"Libellula (1997)","fonte_en":"Dragonfly (1997)","origine":"Karego-At","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestro degli Schemi di Roke","appellativi_en":"Master Patterner of Roke","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Faggio","nome_en":"Beech","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Benderesk","nome_en":"Benderesk","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Osskil","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Signore del Terrenon","appellativi_en":"Lord of the Terrenon","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Barbanera","nome_en":"Blackbeard","vero_nome":"","fonte":"La legge dei nomi (1964)","fonte_en":"The Rule of Names (1964)","origine":"Pendor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Brand","nome_en":"Brand","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Venway","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestro Evocatore di Roke","appellativi_en":"Master Summoner","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Pannocchia","nome_en":"Cob","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Cob","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"signoredraghi":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Corvo","nome_en":"Crow","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Hosk","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Deyala","nome_en":"Deyala","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestro Erborista di Roke","appellativi_en":"Master Herbal","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Duby","nome_en":"Duby","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Eunuco delle Tombe di Atuan","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Duna","nome_en":"Dune","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Elfarran","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Solea","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Regina di Terramare, Regina di Havnor, Signora di Enlad, la Bella","appellativi_en":"-, -, -, the Fair","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Elt","nome_en":"Elt","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Osskil","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Esperto di Nomi","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Nemico di Morred","nome_en":"the Enemy of Morred","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Signore delle Bacchette","nomi_alternativi_en":"the Wandlord","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ennas","nome_en":"Ennas","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Perregal","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"Great Mage of Perregal","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Pioppo","nome_en":"Aspen","vero_nome":"Erisen","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Erreth-Akbe","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Portatore dell'Anello, Costruttore della Torre","nomi_alternativi_en":"","appellativi":"Signore dei Draghi","appellativi_en":"dragonlord","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"signoredraghi":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Rosa","nome_en":"Rose","vero_nome":"Etaudis","fonte":"Libellula (1997)","fonte_en":"Dragonfly (1997)","origine":"Way","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Signore del Fuoco","nome_en":"Firelord","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Selce","nome_en":"Flint","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Azzardo","nome_en":"Gamble","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Gensher","nome_en":"Gensher","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Way","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Arcimago di Roke","appellativi_en":"Archmage","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"arcimago":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Aureo","nome_en":"Golden","vero_nome":"","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Mago Grigio","nome_en":"Grey Mage","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Paln","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Creatore della Sapienza di Paln","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ontano","nome_en":"Alder","vero_nome":"Hara","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Taon","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Alder","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Lepre","nome_en":"Hare","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Wathort","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Hare","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Muschio","nome_en":"Moss","vero_nome":"Hatha","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Melina","nome_en":"Apple","vero_nome":"Hayohe","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Erica","nome_en":"Heather","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Dulse","nome_en":"Dulse","vero_nome":"Heleth","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Il Sagace","nomi_alternativi_en":"Farseer","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Cicuta","nome_en":"Hemlock","vero_nome":"","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Dragone","nome_en":"Highdrake","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Pendor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Segugio","nome_en":"Hound","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ioeth","nome_en":"Ioeth","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Torning","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Avorio","nome_en":"Ivory","vero_nome":"","fonte":"Libellula (1997)","fonte_en":"Dragonfly (1997)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Edera","nome_en":"Ivy","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Diaspro","nome_en":"Jasper","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Jasper","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Kossil","nome_en":"Kossil","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Sacerdotessa del Re Dio di Atuan","appellativi_en":"High Priestess of the Godking","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Kurremkarmerruk","nome_en":"Kurremkarmerruk","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":true,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Lodola","nome_en":"Lark","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Licky","nome_en":"Licky","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Cenerino","nome_en":"Littleash","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Losen","nome_en":"Losen","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Autoproclamato Re del Mare di Mezzo","appellativi_en":"King of the Inmost Sea","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Maharion","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Il Coraggioso, Ultimo Re","nomi_alternativi_en":"","appellativi":"Re di Terramare, Re di Havnor","appellativi_en":"King of All the Isles","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Manan","nome_en":"Manan","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Eunuco delle Tombe di Atuan","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Mead","nome_en":"Mead","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Mebbeth","nome_en":"Mebbeth","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Sacerdotessa delle Tombe di Atuan","appellativi_en":"priestess at the Place of the Tombs","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Giglio","nome_en":"Lily","vero_nome":"Mevre","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Taon","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Morred","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Enlad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Il Bianco, Eroe-mago di Havnor","nomi_alternativi_en":"the White, Hero-Mage of Havnor","appellativi":"Re di Terramare, Re di tutte le isole","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"signoredraghi":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Gazzamarina","nome_en":"Murre","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Iffish","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Nemmerle","nome_en":"Nemmerle","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestro degli Schemi di Roke, Arcimago di Roke","appellativi_en":"Master Patterner, Archmage","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"arcimago":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Nereger","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Paln","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Nesty","nome_en":"Nesty","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Onice","nome_en":"Onyx","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Libellula","nome_en":"Dragonfly","vero_nome":"Orm Irian","fonte":"Libellula (1997)","fonte_en":"Dragonfly (1997)","origine":"Way","genere":"f","padre":"","madre":"","tipo":"Donna | Drago","tipo_en":"Woman | Dragon","tipo_color":"type-donnadrago|","nomi_alternativi":"Irian","nomi_alternativi_en":"Irian","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Pechvarry","nome_en":"Pechvarry","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Torning","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Penthe","nome_en":"Penthe","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Terre di Kargad","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Mago Rosso di Ark","nome_en":"Red Mage of Ark","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Ark","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Rosa","nome_en":"Rose","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Rosa","nome_en":"Darkrose","vero_nome":"","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Rosascura","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Rosa","nome_en":"Rose","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Enlad","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sorbo","nome_en":"Rowan","vero_nome":"","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Seppel","nome_en":"Seppel","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Paln","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Serrathen","nome_en":"Serrathen","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Serret","nome_en":"Serret","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Serriadh","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Enlad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Il Re Gentile, il Pacificatore","nomi_alternativi_en":"the gentle king, the peacemaker","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Seserakh","nome_en":"Seserakh","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Terre di Kargad","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Principessa delle Terre di Kargad","appellativi_en":"High Princess of the Kargad Lands","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Skiorh","nome_en":"Skiorh","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"Osskil","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sopli","nome_en":"Sopli","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Lorbanery","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Scintilla","nome_en":"Spark","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Groviglio","nome_en":"Tangle","vero_nome":"","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Thar","nome_en":"Thar","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Sacerdotessa degli Dei Gemelli di Atuan","appellativi_en":"High Priestess of the Twin Gods","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Thol","nome_en":"Thol","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Terre di Kargad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Re delle Terre di Kargad","appellativi_en":"High King of the Four Kargad Lands","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"","nome_en":"","vero_nome":"Thorion","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Roke","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Maestro delle Evocazioni di Roke","appellativi_en":"Master Summoner","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"maestro":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Tuly","nome_en":"Tuly","vero_nome":"","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"Havnor","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Uahto","nome_en":"Uahto","vero_nome":"","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"Atuan","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Eunuco delle Tombe di Atuan","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Velo","nome_en":"Veil","vero_nome":"Yahan","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"Roke","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"}
];
