var datiVersion = "0.01";
// Colori delle due razze. ⚠️ Valori PROVVISORI: chiari e desaturati per scelta
// dell'utente, ma da misurare sul gate di contrasto AA nei due temi.
var cardColors = {"fam":{"man":{"dark":"#d9c089","light":"#9c7c3a"},"dragon":{"dark":"#e0a090","light":"#b25a48"}},"map":{"type-man":"man","type-dragon":"dragon"}};
// ⚠️⚠️ DATASET DI PARTENZA, NON ANCORA VERIFICATO SULLE FONTI.
// Contiene SOLO quello che l'utente ha dichiarato a memoria il 2026-08-20: nome d'uso,
// vero nome fra parentesi, e quali sono draghi. Tutto il resto è volutamente vuoto:
// origine, genere, parentele, descrizioni e fonti non sono attestati da nulla che sia
// in scena, e riempirli a memoria è esattamente ciò che la regola vieta.
var dati = [
{"nome":"Ogion","nome_en":"Ogion","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Aihal","nomi_alternativi_en":"Aihal","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Veccia","nome_en":"Veccia","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Estarriol","nomi_alternativi_en":"Estarriol","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Millefoglie","nome_en":"Millefoglie","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Kest","nomi_alternativi_en":"Kest","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Arha / Goha","nome_en":"Arha / Goha","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Tenar","nomi_alternativi_en":"Tenar","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Arren","nome_en":"Arren","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Lebannen","nomi_alternativi_en":"Lebannen","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Therru","nome_en":"Therru","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Tehanu","nomi_alternativi_en":"Tehanu","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Dote","nome_en":"Dote","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Emer","nomi_alternativi_en":"Emer","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Orm Embar","nome_en":"Orm Embar","fonte":"","fonte_en":"","paese":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Kalessin","nome_en":"Kalessin","fonte":"","fonte_en":"","paese":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Yevaud","nome_en":"Yevaud","fonte":"","fonte_en":"","paese":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Lontra / Sterna","nome_en":"Lontra / Sterna","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Medra","nomi_alternativi_en":"Medra","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Giaggiolo","nome_en":"Giaggiolo","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Anieb","nomi_alternativi_en":"Anieb","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Gelluk","nome_en":"Gelluk","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Tinaral","nomi_alternativi_en":"Tinaral","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Brace","nome_en":"Brace","fonte":"","fonte_en":"","paese":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Elehal","nomi_alternativi_en":"Elehal","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Early","nome_en":"Early","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Teriel","nomi_alternativi_en":"Teriel","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Diamante","nome_en":"Diamante","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Essiri","nomi_alternativi_en":"Essiri","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Burrone / Otak","nome_en":"Burrone / Otak","fonte":"","fonte_en":"","paese":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Irioth","nomi_alternativi_en":"Irioth","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"citazione":"","citazione_en":"","divino":false,"veronome":true,"descrizione":"","descrizione_en":"","cardcolor":"man"}
];
