var datiVersion = "0.49";
// Colori delle due razze. ⚠️ Valori PROVVISORI: chiari e desaturati per scelta
// dell'utente, ma da misurare sul gate di contrasto AA nei due temi.
// ⚠️ Questa riga VINCE sul fallback dentro index.html: e' la configurazione salvata,
// e al cambio di tavolozza (2026-08-21) i valori vecchi restavano attivi mentre il
// fallback diceva un'altra cosa. Chi cambia una tinta la cambia QUI.
// Quattro famiglie e tre categorie: la tinta degli umani segue il genere (vedi
// `familyOf`), quella degli animali no, perché fra loro il genere manca spesso.
var cardColors = {"fam":{"man":{"dark":"#9cb2f0","light":"#22449c"},"woman":{"dark":"#6fd0d6","light":"#0c757e"},"dragon":{"dark":"#e0a090","light":"#a8462f"},"animale":{"dark":"#e6c445","light":"#856508"}},"map":{"type-man":"man","type-dragon":"dragon","type-animale":"animale"}};
var siteFlags = {"zoomBig":false,"glow":{"on":true,"all":true,"pl":true,"pr":false,"ps":false,"pa":false,"amp_d":60,"amp_l":60,"int_d":0.18,"int_l":0.18,"oamp_d":11,"oamp_l":40,"oint_d":0.9,"oint_l":0.22,"aamp_d":20,"aamp_l":20,"aint_d":0.3,"aint_l":0.11},"glow_m":{"on":true,"all":false,"pl":true,"pr":false,"ps":false,"pa":false,"amp_d":34,"amp_l":34,"int_d":0.62,"int_l":0.5,"oamp_d":11,"oamp_l":11,"oint_d":0.9,"oint_l":0.69,"aamp_d":20,"aamp_l":20,"aint_d":0.3,"aint_l":0.22},"spot":{"on":false,"r":170,"int":0.09},"spot_m":{"on":true,"r":170,"int":0.09},"press":{"on":true,"name":true,"lab":true,"num":true},"press_m":{"on":true,"name":true,"lab":true,"num":false},"vig":{"on":true,"int":0.25,"start":38},"vig_m":{"on":true,"int":0.34,"start":38},"podium":{"on":false,"int_d":1,"int_l":1,"lum_d":1,"lum_l":1,"sat_d":1,"sat_l":1,"top_d":0.7,"top_l":0.7,"rifl_d":0.8,"rifl_l":0.8,"crisp_d":0,"crisp_l":0,"tamp_d":18,"tamp_l":18},"podium_m":{"on":true,"int_d":1,"int_l":1,"lum_d":1,"lum_l":1,"sat_d":1,"sat_l":1,"top_d":0.7,"top_l":0.7,"rifl_d":0.8,"rifl_l":0.8,"crisp_d":0,"crisp_l":0,"tamp_d":18,"tamp_l":18},"nums":{"on":true,"uni":false,"dsat":0.55,"dlum":0.78,"lsat":0.5,"llum":0.52},"nums_m":{"on":true,"uni":true,"dsat":0.15,"dlum":0.66,"lsat":0.15,"llum":0.6},"hov":{"on":true,"bd":true,"op_d":0.09,"op_l":0.08,"sat_d":0.55,"sat_l":0.5,"lum_d":1,"lum_l":1.12},"hov_m":{"on":true,"bd":true,"op_d":0.18,"op_l":0.11,"sat_d":1,"sat_l":1,"lum_d":1,"lum_l":1},"pat":{"on":true,"mot":"banner","c_d":"#ffffff","op_d":0.08,"c_l":"#000000","op_l":0.1,"sc":1,"fade":130},"pat_m":{"on":false,"mot":"stars","c_d":"#ffffff","op_d":0.055,"c_l":"#000000","op_l":0.05,"sc":1,"fade":120}};
// ⚠️⚠️ DATASET DI PARTENZA, NON ANCORA VERIFICATO SULLE FONTI.
// Contiene SOLO quello che l'utente ha dichiarato a memoria (il 2026-08-20 le prime voci,
// il 2026-08-21 Sparviero e Solevivo): nome d'uso, vero nome fra parentesi, e quali sono
// draghi. ⚠️ `nome_en` ripete l'italiano di proposito: le rese inglesi non sono in scena, e
// tradurne una sola (Sparviero -> Sparrowhawk) farebbe sembrare attestate anche le altre.
// ⚠️ Il badge `nomeged` ('Custode del vero nome di Ged') è acceso sulle NOVE voci che
// il canone elenca (`rules/Earthsea.md`, § 'Chi conobbe il vero nome di Sparviero'): Ogion,
// Veccia, Millefoglie, Arha / Goha, Arren, Therru / Tehanu, Dote, Orm Embar, Kalessin. Quel file è
// la sua UNICA fonte: non si ricava dalla scheda di un personaggio, quindi non si deduce e
// non si aggiunge a intuito. Kurremkarmerruk è nell'elenco ma non ancora nel dataset, e i
// due maestri di Roke senza nome sono esclusi per scelta dell'utente.
// ⚠️ Sparviero NON lo porta, e non è una dimenticanza: il badge marca chi ricevette in
// custodia il suo nome, non chi lo porta.
// Ha preso il posto di `veronome`, che diceva 'di questo personaggio si conosce il vero
// nome': informazione che la riga del vero nome ora dà da sé.
// ⚠️ `fonte_en` è l'opera di PRIMA APPARIZIONE, presa dalla parentesi della voce Wikipedia
// 'List of Earthsea characters' (letta il 2026-08-21) e quindi col titolo INGLESE; `fonte`
// resta vuoto perché è il posto del titolo italiano, che nessuna fonte in scena attesta.
// Arren e Sparviero non l'hanno: in quella voce la parentesi non c'è, e dedurla a memoria
// (per ovvia che sia) sarebbe esattamente quello che la regola vieta. Tutto il resto è volutamente vuoto:
// origine, genere, parentele, descrizioni e fonti non sono attestati da nulla che sia
// in scena, e riempirli a memoria è esattamente ciò che la regola vieta.
// ⚠️ I badge `signoredraghi` e `arcimago` (dal 2026-08-23) sono accesi sul solo
// Sparviero, e su UNA frase attestata: l'apertura di 'Un mago di Terramare' dice che
// 'nei suoi giorni mortali divenne Signore dei Draghi e Arcimago'. Non si estendono a
// intuito: il criterio del primo (chi è drago NON lo porta) sta in questo `CLAUDE.md`,
// le attestazioni degli altri portatori in `rules/Earthsea.md`, e le loro voci non sono
// ancora nel dataset. ⚠️ Il terzo badge nuovo, `maestro`, non ha ancora NESSUN portatore:
// non è una dimenticanza, è che nessuno dei nove Maestri di Roke è nel dataset.
// ⚠️ Le due voci in coda, **Sege** e **Tosla**, sono le PRIME verificate sulle fonti
// invece che dichiarate a memoria (2026-08-23, su richiesta dell'utente, e senza passare
// dallo Schedario: sua deroga esplicita). Che cosa è attestato e che cosa no sta in
// `CLAUDE.md`, § 'Sege e Tosla'.
// ⚠️ Il campo dell'origine geografica si chiama `origine`, come la voce omonima dello
// Schedario, e dalla `0.45` ha preso il posto di `paese`, che era un residuo del motore di
// provenienza (`gb` su tutte e 360 le voci di Arda) e non lo leggeva nessuno. Storia in
// `CLAUDE.md`, § 'Il campo origine'.
// ⚠️ `origine` è pieno per **Sege** (`Havnor`, attestato) e VUOTO per **Tosla**, perché di
// lui il testo non dice mai da dove venga: il vuoto è un dato, non un campo da riempire.
// ⚠️⚠️ LE 17 VOCI IN CODA (dalla `0.47`, 2026-08-23) sono verificate col grep sugli epub,
// una per una, e non dichiarate a memoria: 12 ANIMALI (la categoria nuova), Keor, Sula, e i
// tre draghi Bar Oth, Ammaud e Orm. Le attestazioni e i tre punti dove il testo dice una
// cosa diversa da quella che l'utente ricordava stanno in `CLAUDE.md`, § 'Gli animali'.
// ⚠️ `tipo` di un animale è l'ANIMALE VERO (`Gatta`, `Gallo`), non la categoria: la
// categoria unica 'Animali' la ricava il motore dall'elenco `TIPI_ANIMALE` in
// `index.html`, ed è là che va aggiunto un animale nuovo, o la sua card finisce fra gli
// uomini senza dare alcun errore.
// ⚠️ IL GENERE DEI DRAGHI È PIENO SU TRE VOCI SOLE, e le altre restano vuote di proposito
// (elenco chiuso dall'utente il 2026-08-23): **Tehanu** e **Orm Irian** femmine perché sono
// donne oltre che draghi, **Ammaud** maschio perché è Orm Irian a chiamarlo *mio fratello*,
// cioè un drago che parla della propria famiglia. ⚠️ `Orm` NON lo prende benché il testo dica
// *tuo padre Orm*: là il maschile è la convenzione con cui gli uomini nominano un drago.
// Il criterio, con la frase del canone che lo chiude, e l'elenco dei cinque che restano senza,
// stanno in `rules/Earthsea.md`, § 'Il genere dei draghi: congettura, non dato'.
// ⚠️⚠️ I SEI DRAGHI PURI HANNO IL DATO INVERTITO, e va raddrizzato: un drago ha **solo** il
// vero nome, quindi il campo vuoto deve essere `nome` e `vero_nome` deve portare il nome
// (`Kalessin`), non il contrario come adesso. Correzione dell'utente del 2026-08-23 su un
// malinteso vecchio: *è una differenza sostanziale... è uno dei punti-chiave del dataset*.
// ⚠️ Non si tocca finché non arrivano i personaggi dello Schedario, che nasceranno già nella
// forma giusta: migrare due volte costa il doppio. Le voci e che cosa cambia nel motore stanno
// in `CLAUDE.md`, § 'Il DATO è INVERTITO, e va raddrizzato: il campo vuoto è il nome comune'.
// ⚠️ Le due IBRIDE sono FUORI da quella migrazione, e dalla `0.48` seguono la regola umana:
// **Tehanu** porta `nome` `Therru` e `vero_nome` `Tehanu` (istruzione dell'utente: *gli ibridi
// sono eccezioni e ragionano a sé... dopotutto le due sono ANCHE umane*), e `Orm Irian` nascerà
// con `Libellula` davanti.
// ⚠️ Ma la regola umana vale per la RESA, non per la categoria: un'ibrida appartiene a
// ENTRAMBE (`Donna | Drago`), quindi compare sia coi soli Umani accesi sia coi soli Draghi. Sono
// due livelli indipendenti, ed è la precisazione dell'utente del 2026-08-23.
// ⚠️ `origine` degli animali è `Gont` per tutti e dodici, ed è la RESIDENZA attestata (la
// casa di zia Muschio, Dieci Ontani, il pollaio di Re Albi), non un luogo di nascita: la
// regola ammette la residenza in mancanza della nascita, e di un pollo non si dice dove sia
// nato. Per **Sula** vale lo stesso (`Taon`, dove insegnava ad Alder), e l'utente l'ha
// dichiarato lui stesso scrivendo *origine (non per nascita)*.
var dati = [
{"nome":"Sparviero","nome_en":"Sparviero","vero_nome":"Ged","fonte":"","fonte_en":"","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Falco","nomi_alternativi_en":"Falco","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"signoredraghi":true,"arcimago":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Ogion","nome_en":"Ogion","vero_nome":"Aihal","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Veccia","nome_en":"Veccia","vero_nome":"Estarriol","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Millefoglie","nome_en":"Millefoglie","vero_nome":"Kest","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Goha","nome_en":"Goha","vero_nome":"Tenar","fonte":"Le tombe di Atuan (1970)","fonte_en":"The Tombs of Atuan (1970)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"Arha","nomi_alternativi_en":"Arha","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Arren","nome_en":"Arren","vero_nome":"Lebannen","fonte":"","fonte_en":"","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Therru","nome_en":"Therru","vero_nome":"Tehanu","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna | Drago","tipo_en":"Woman | Dragon","tipo_color":"type-donnadrago|","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Dote","nome_en":"Dote","vero_nome":"Emer","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Orm Embar","nome_en":"Orm Embar","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Kalessin","nome_en":"Kalessin","vero_nome":"","fonte":"Tehanu (1990)","fonte_en":"Tehanu (1990)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":true,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Yevaud","nome_en":"Yevaud","vero_nome":"","fonte":"La legge dei nomi (1964)","fonte_en":"The Rule of Names (1964)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Lontra","nome_en":"Lontra","vero_nome":"Medra","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Sterna","nomi_alternativi_en":"Sterna","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Giaggiolo","nome_en":"Giaggiolo","vero_nome":"Anieb","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Gelluk","nome_en":"Gelluk","vero_nome":"Tinaral","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Brace","nome_en":"Brace","vero_nome":"Elehal","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"f","padre":"","madre":"","tipo":"Donna","tipo_en":"Woman","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Early","nome_en":"Early","vero_nome":"Teriel","fonte":"Il Trovatore (2001)","fonte_en":"The Finder (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Diamante","nome_en":"Diamante","vero_nome":"Essiri","fonte":"Rosascura e Diamante (1999)","fonte_en":"Darkrose and Diamond (1999)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Burrone","nome_en":"Burrone","vero_nome":"Irioth","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"Otak","nomi_alternativi_en":"Otak","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"mago":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Solevivo","nome_en":"Solevivo","vero_nome":"Ayeth","fonte":"Nell'Alta Palude (2001)","fonte_en":"On the High Marsh (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sege","nome_en":"Sege","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Havnor","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Principe della Casa di Havnor","appellativi_en":"Prince of the House of Havnor","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Tosla","nome_en":"Tosla","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Grigina","nome_en":"Little Grey","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gatta","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gatta di zia Muschio","info_en":"Aunty Moss's cat","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Nerone","nome_en":"Old Black","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Gatto","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gatto di zia Muschio","info_en":"Aunty Moss's cat","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Biddy","nome_en":"Biddy","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di zia Muschio","info_en":"Aunty Moss's hen","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Fioccodineve","nome_en":"Snowflakes","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di zia Muschio","info_en":"Aunty Moss's hen","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Vaiavanti","nome_en":"Gobefore","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Cane","tipo_en":"Dog","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Cane della zia di Sparviero, a Dieci Ontani","info_en":"Sparrowhawk's aunt's dog, at Ten Alders","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Tiro","nome_en":"Tug","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Gont","genere":"","padre":"","madre":"Grigina","madre_en":"Little Grey","tipo":"Gatto","tipo_en":"Cat","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Bucca Rossa","nome_en":"Red Bucca","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Bucca Bruna","nome_en":"Brown Bucca","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Grigia","nome_en":"Grey","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Candore","nome_en":"Candor","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Ghette","nome_en":"Leggings","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"f","padre":"","madre":"","tipo":"Gallina","tipo_en":"Hen","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallina di Heleth, a Re Albi","info_en":"Heleth's hen, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Il Re","nome_en":"The King","vero_nome":"","fonte":"Le ossa della terra (2001)","fonte_en":"The Bones of the Earth (2001)","origine":"Gont","genere":"m","padre":"","madre":"","tipo":"Gallo","tipo_en":"Rooster","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"Gallo di Heleth, a Re Albi","info_en":"Heleth's rooster, at Re Albi","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"animale"},
{"nome":"Keor","nome_en":"Keor","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"Enlad","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"Principe di Enlad","appellativi_en":"Prince of Enlad","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Sula","nome_en":"Gannet","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"Taon","genere":"m","padre":"","madre":"","tipo":"Uomo","tipo_en":"Man","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"stregone":true,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"man"},
{"nome":"Bar Oth","nome_en":"Bar Oth","vero_nome":"","fonte":"La spiaggia più lontana (1972)","fonte_en":"The Farthest Shore (1972)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Ammaud","nome_en":"Ammaud","vero_nome":"","fonte":"I venti di Terramare (2001)","fonte_en":"The Other Wind (2001)","origine":"","genere":"m","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"},
{"nome":"Orm","nome_en":"Orm","vero_nome":"","fonte":"Un mago di Terramare (1968)","fonte_en":"A Wizard of Earthsea (1968)","origine":"","genere":"","padre":"","madre":"","tipo":"Drago","tipo_en":"Dragon","nomi_alternativi":"","nomi_alternativi_en":"","appellativi":"","appellativi_en":"","info":"","info_en":"","featured":false,"divino":false,"nomeged":false,"descrizione":"","descrizione_en":"","cardcolor":"dragon"}
];
